# Generated by Django 3.2 on 2021-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usedquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordque', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(null=True)),
                ('miss', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='Choice_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Question_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Word_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='Sound',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='Sound',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='Type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='Choice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='Icon',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='Question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='Sound',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='Word_th',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
