# Generated by Django 3.2 on 2021-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='Choice_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Question_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Word_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='Sound',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Sound',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
