# Generated by Django 3.2 on 2021-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karen', '0002_auto_20210428_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Icon',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
